name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          cargo build --verbose --all
      - name: Test
        run: |
          curl -fSL https://github.com/cocoa-xu/evision/releases/download/v0.1.34/evision-nif_2.17-aarch64-linux-gnu-0.1.34.tar.gz -o evision-nif_2.17-aarch64-linux-gnu-0.1.34.tar.gz
          tar -xf evision-nif_2.17-aarch64-linux-gnu-0.1.34.tar.gz
          cargo run -- --help
          cargo run -- -p evision-nif_2.17-aarch64-linux-gnu-0.1.34/priv/evision.so --stdout=json --pretty-json --detail-level=version
          cargo run -- -p evision-nif_2.17-aarch64-linux-gnu-0.1.34/priv/evision.so --stdout=json --pretty-json --detail-level=function
          cargo run -- -p evision-nif_2.17-aarch64-linux-gnu-0.1.34/priv/evision.so --stdout=json --pretty-json --detail-level=file
  